import { SampleVideoItem } from '../src/types';

export const SAMPLE_VIDEOS: SampleVideoItem[] = [
  {
    id: 'douyin-skincare-viral',
    platform: 'douyin',
    title: 'Douyin Skincare: 3 Bước Trị Mụn Ẩn Cấp Tốc Bằng Salicylic Acid',
    niche: 'Mỹ phẩm & Skincare (Tiếng Trung)',
    description: 'Video Douyin 2.4M likes - Kịch bản gốc Tiếng Trung và Bản dịch Tiếng Việt.',
    url: 'https://v.douyin.com/iJkLmNoP/',
    badge: 'Tiếng Trung (Douyin) • 2.4M Likes',
    sampleResult: {
      sourceLanguage: 'zh',
      sourceLanguageName: 'Tiếng Trung (Douyin)',
      isVietnamese: false,
      videoMetadata: {
        url: 'https://v.douyin.com/iJkLmNoP/',
        platform: 'douyin',
        title: 'Douyin Skincare: 3 Bước Trị Mụn Ẩn Cấp Tốc Bằng Salicylic Acid',
        author: '@美妆学姐 (Tiểu Tuyết Skincare)',
        duration: 28,
      },
      segments: [
        {
          id: 'seg_1',
          timestamp: '[00:00 - 00:04]',
          startSec: 0,
          endSec: 4,
          originalText: '如果你的脸上总是有这种密密麻麻的闭口粉刺，千万别去美容院乱挤！',
          translatedText: 'Nếu mặt bạn đang chi chít mụn ẩn li ti thế này, xin đừng dại mà đi spa nặn bừa bãi!',
        },
        {
          id: 'seg_2',
          timestamp: '[00:04 - 00:09]',
          startSec: 4,
          endSec: 9,
          originalText: '不仅留坑留印，毛孔还会越来越粗大。其实在家只要用好这瓶水杨酸棉片。',
          translatedText: 'Vừa để lại thâm rỗ, lỗ chân lông lại càng to ngoác ra. Thật ra ở nhà chỉ cần dùng đúng hũ bông Salicylic Acid này thôi.',
        },
        {
          id: 'seg_3',
          timestamp: '[00:09 - 00:15]',
          startSec: 9,
          endSec: 15,
          originalText: '先用凸起面轻轻打圈擦拭T区30秒，溶解深层油脂角质；再用平滑面湿敷在闭口处3分钟。',
          translatedText: 'Đầu tiên dùng mặt vân nổi mát-xa nhẹ vùng chữ T trong 30 giây để hòa tan dầu thừa bít tắc; sau đó đắp mặt phẳng lên chỗ mụn ẩn 3 phút.',
        },
        {
          id: 'seg_4',
          timestamp: '[00:15 - 00:21]',
          startSec: 15,
          endSec: 21,
          originalText: '坚持一周，你摸摸你的脸蛋，是不是像剥了壳的鸡蛋一样滑嫩透亮？',
          translatedText: 'Kiên trì đúng 1 tuần, bạn tự sờ lên má xem, da có láng mịn căng mọng như trứng gà bóc không?',
        },
        {
          id: 'seg_5',
          timestamp: '[00:21 - 00:28]',
          startSec: 21,
          endSec: 28,
          originalText: '今天左下角品牌方做活动，买一盒送一盒还包邮，赶紧去囤两盒！',
          translatedText: 'Hôm nay nhãn hàng đang trợ giá góc trái màn hình, mua 1 tặng 1 lại còn freeship, các bà ấn nhanh kẻo hết deal!',
        },
      ],
      fullOriginalScript: '如果你的脸上总是有这种密密麻麻的闭口粉刺，千万别去美容院乱挤！不仅留坑留印，毛孔还会越来越粗大。其实在家只要用好这瓶水杨酸棉片。先用凸起面轻轻打圈擦拭T区30秒，溶解深层油脂角质；再用平滑面湿敷在闭口处3分钟。坚持一周，你摸摸你的脸蛋，是不是像剥了壳的鸡蛋一样滑嫩透亮？今天左下角品牌方做活动，买一盒送一盒还包邮，赶紧去囤两盒！',
      fullTranslatedScript: 'Nếu mặt bạn đang chi chít mụn ẩn li ti thế này, xin đừng dại mà đi spa nặn bừa bãi! Vừa để lại thâm rỗ, lỗ chân lông lại càng to ngoác ra. Thật ra ở nhà chỉ cần dùng đúng hũ bông Salicylic Acid này thôi. Đầu tiên dùng mặt vân nổi mát-xa nhẹ vùng chữ T trong 30 giây để hòa tan dầu thừa bít tắc; sau đó đắp mặt phẳng lên chỗ mụn ẩn 3 phút. Kiên trì đúng 1 tuần, bạn tự sờ lên má xem, da có láng mịn căng mọng như trứng gà bóc không? Hôm nay nhãn hàng đang trợ giá góc trái màn hình, mua 1 tặng 1 lại còn freeship, các bà ấn nhanh kẻo hết deal!',
    },
  },
  {
    id: 'tiktok-gadget-review',
    platform: 'tiktok',
    title: 'TikTok Tech Review: Đừng Mua Bàn Phím Cơ Đắt Tiền Nếu Chưa Biết Con Này',
    niche: 'Công nghệ & Setup (Tiếng Việt)',
    description: 'Video review bàn phím cơ bằng Tiếng Việt 1.8M views.',
    url: 'https://www.tiktok.com/@techgenz/video/7328918239123891',
    badge: 'Tiếng Việt • 1.8M Views',
    sampleResult: {
      sourceLanguage: 'vi',
      sourceLanguageName: 'Tiếng Việt',
      isVietnamese: true,
      videoMetadata: {
        url: 'https://www.tiktok.com/@techgenz/video/7328918239123891',
        platform: 'tiktok',
        title: 'TikTok Tech Review: Đừng Mua Bàn Phím Cơ Đắt Tiền Nếu Chưa Biết Con Này',
        author: '@TechSavvyGenz (Reviewer Công Nghệ)',
        duration: 32,
      },
      segments: [
        {
          id: 'seg_1',
          timestamp: '[00:00 - 00:05]',
          startSec: 0,
          endSec: 5,
          originalText: 'Dừng lại ngay! Nếu bạn đang định bỏ ra 2 củ để mua bàn phím cơ thì hãy xem hết video này để không bị mất tiền ngu.',
        },
        {
          id: 'seg_2',
          timestamp: '[00:05 - 00:12]',
          startSec: 5,
          endSec: 12,
          originalText: 'Đây là con bàn phím cơ không dây 3 mode kết nối, switch đã được lube sẵn từ nhà máy, gõ êm mượt mà giá chưa tới 500 cành.',
        },
        {
          id: 'seg_3',
          timestamp: '[00:12 - 00:20]',
          startSec: 12,
          endSec: 20,
          originalText: 'Mọi người nghe thử tiếng gõ này xem có đầm tai không? Đèn LED RGB 16 triệu màu, pin dùng cả tháng mới phải sạc lại một lần.',
        },
        {
          id: 'seg_4',
          timestamp: '[00:20 - 00:26]',
          startSec: 20,
          endSec: 26,
          originalText: 'Kết nối được cùng lúc cả Mac, Windows và điện thoại, chuyển đổi chỉ bằng một nút gạt cực kỳ tiện lợi cho anh em dân văn phòng.',
        },
        {
          id: 'seg_5',
          timestamp: '[00:26 - 00:32]',
          startSec: 26,
          endSec: 32,
          originalText: 'Link mua chính hãng kèm mã giảm 50k mình để ở góc trái, số lượng deal có hạn anh em múc ngay nhé!',
        },
      ],
      fullOriginalScript: 'Dừng lại ngay! Nếu bạn đang định bỏ ra 2 củ để mua bàn phím cơ thì hãy xem hết video này để không bị mất tiền ngu. Đây là con bàn phím cơ không dây 3 mode kết nối, switch đã được lube sẵn từ nhà máy, gõ êm mượt mà giá chưa tới 500 cành. Mọi người nghe thử tiếng gõ này xem có đầm tai không? Đèn LED RGB 16 triệu màu, pin dùng cả tháng mới phải sạc lại một lần. Kết nối được cùng lúc cả Mac, Windows và điện thoại, chuyển đổi chỉ bằng một nút gạt cực kỳ tiện lợi cho anh em dân văn phòng. Link mua chính hãng kèm mã giảm 50k mình để ở góc trái, số lượng deal có hạn anh em múc ngay nhé!',
      fullTranslatedScript: undefined,
    },
  },
  {
    id: 'douyin-food-viral',
    platform: 'douyin',
    title: 'Douyin F&B: Nghệ Thuật Kịch Bản Bán Nồi Lẩu Tự Sôi Cay Tứ Xuyên',
    niche: 'Ẩm thực & Đồ ăn (Tiếng Trung)',
    description: 'Video Douyin ẩm thực triệu view - Kịch bản gốc Tiếng Trung và Bản dịch Tiếng Việt.',
    url: 'https://v.douyin.com/mNoPqRsT/',
    badge: 'Tiếng Trung (Douyin) • 3.1M Likes',
    sampleResult: {
      sourceLanguage: 'zh',
      sourceLanguageName: 'Tiếng Trung (Douyin)',
      isVietnamese: false,
      videoMetadata: {
        url: 'https://v.douyin.com/mNoPqRsT/',
        platform: 'douyin',
        title: 'Douyin F&B: Nghệ Thuật Kịch Bản Bán Nồi Lẩu Tự Sôi Cay Tứ Xuyên',
        author: '@深夜放毒 (Đầu Bếp Đêm Douyin)',
        duration: 25,
      },
      segments: [
        {
          id: 'seg_1',
          timestamp: '[00:00 - 00:04]',
          startSec: 0,
          endSec: 4,
          originalText: '大半夜肚子饿又懒得下楼，千万别点三四十块的外卖！',
          translatedText: 'Nửa đêm bụng réo cồn cào mà ngại xuống đường, các bác đừng vội gọi bát phở ship mấy chục nghìn!',
        },
        {
          id: 'seg_2',
          timestamp: '[00:04 - 00:10]',
          startSec: 4,
          endSec: 10,
          originalText: '就拆一盒这个麻辣自热小火锅，不用插电不用开火，倒上一杯凉水只要15分钟。',
          translatedText: 'Cứ xé ngay một hộp lẩu tự sôi cay Tứ Xuyên này, không cần cắm điện chẳng cần nhóm bếp, rót cốc nước lọc đợi đúng 15 phút.',
        },
        {
          id: 'seg_3',
          timestamp: '[00:10 - 00:18]',
          startSec: 10,
          endSec: 18,
          originalText: '你看这大片的牛肉、爽脆的毛肚，还有吸满浓郁红油汤汁的宽粉，吸溜一口香迷糊了！',
          translatedText: 'Mọi người nhìn miếng thịt bò to bự chảng, sách bò giòn sần sật, sợi miến dẹt ngập đẫm nước lẩu sa tế thơm lừng, húp một miếng là tỉnh cả người!',
        },
        {
          id: 'seg_4',
          timestamp: '[00:18 - 00:25]',
          startSec: 18,
          endSec: 25,
          originalText: '厂家冲销量，今天拍一发四，算下来一顿才几块钱，左下角手慢无！',
          translatedText: 'Xưởng đang xả kho chạy số, hôm nay đặt 1 được 4 hộp tính ra mỗi bữa chỉ bằng cốc trà đá, góc trái số lượng có hạn chốt lẹ kẻo tiếc!',
        },
      ],
      fullOriginalScript: '大半夜肚子饿又懒得下楼，千万别点三四十块的外卖！就拆一盒这个麻辣自热小火锅，不用插电不用开火，倒上一杯凉水只要15分钟。你看这大片的牛肉、爽脆的毛肚，还有吸满浓郁红油汤汁的宽粉，吸溜一口香迷糊了！厂家冲销量，今天拍一发四，算下来一顿才几块钱，左下角手慢无！',
      fullTranslatedScript: 'Nửa đêm bụng réo cồn cào mà ngại xuống đường, các bác đừng vội gọi bát phở ship mấy chục nghìn! Cứ xé ngay một hộp lẩu tự sôi cay Tứ Xuyên này, không cần cắm điện chẳng cần nhóm bếp, rót cốc nước lọc đợi đúng 15 phút. Mọi người nhìn miếng thịt bò to bự chảng, sách bò giòn sần sật, sợi miến dẹt ngập đẫm nước lẩu sa tế thơm lừng, húp một miếng là tỉnh cả người! Xưởng đang xả kho chạy số, hôm nay đặt 1 được 4 hộp tính ra mỗi bữa chỉ bằng cốc trà đá, góc trái số lượng có hạn chốt lẹ kẻo tiếc!',
    },
  },
];
